# vim: ft=ansible :
---
- name: Include OS specific variable
  include_vars: "{{ ansible_os_family }}.yml"

- name: Set facts
  set_fact:
    "{{ 'influxdb_' + item }}" : "{{ vars['__influxdb_' + item] }}"
  with_items:
    - package_version
    - user
    - group
    - data_dir
    - meta_dir
    - hh_dir
    - wal_dir
    - generated_config
    - config_file
    - influxd_bin
  register:
  when: ( vars['influxdb_' + item] is undefined)

- include: "{{ ansible_os_family }}.yml"

- name: Create influxdb group
  group:
    name: "{{ influxdb_group }}"
    state: present

- name: Create influxdb user
  user:
    name: "{{ influxdb_user }}"
    group: "{{ influxdb_group }}"
    state: present

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    group: "{{ influxdb_group }}"
    owner: "{{ influxdb_user }}"
  with_items:
    - "{{ influxdb_data_dir }}"
    - "{{ influxdb_meta_dir }}"
    - "{{ influxdb_hh_dir }}"
    - "{{ influxdb_wal_dir }}"
    - "{{ influxdb_config_dir }}"

- name: Write config
  template:
    src: conf.j2
    dest: "{{ influxdb_generated_config }}"
    group: "{{ influxdb_group }}"
    owner: "{{ influxdb_user }}"
  register: write_config

# TODO: Find out why this doesn't work
# TODO: Update to use Ansible 2.0 run as instead of sudo
- name: Run config update
  command: "{{ influxdb_influxd_bin }} config -config {{ influxdb_generated_config }}"
  register: influxdb_merged_config

- name: Write merged config
  copy:
    remote_src: True
    src: "{{ influxdb_generated_config }}"
    dest: "{{ influxdb_config_file }}"
    group: "{{ influxdb_group }}"
    owner: "{{ influxdb_user }}"

- name: Ensure directories have correct permissions
  file:
    path: "{{ item }}"
    owner: "{{ influxdb_user }}"
    group: "{{ influxdb_group }}"
    recurse: yes
  with_items:
    - "{{ influxdb_meta_dir }}"
    - "{{ influxdb_data_dir }}"
    - "{{ influxdb_hh_dir }}"
    - "{{ influxdb_wal_dir }}"

- block:
  - name: Start master node
    service:
      name: influxdb
      state: started
      enabled: yes
    when: influxdb_cluster_master == ansible_hostname
  - name: Wait for master
    wait_for:
      host: "{{ ansible_hostname }}"
      port: 8088
      state: started
    when: influxdb_cluster_master == ansible_hostname
  - name: Join the cluster
    lineinfile:
      path: /etc/default/influxdb
      create: yes
      regexp: '^INFLUXD_OPTS='
      line: "INFLUXD_OPTS=\"-join {{ influxdb_cluster_master }}:8088\""
    register: influxdb_cluster_join
    when:
    - influxdb_cluster_master != ansible_hostname
  - name: Add node to the cluster
    service:
      name: influxdb
      state: started
      enabled: yes
    when:
    - influxdb_cluster_master != ansible_hostname
    - influxdb_cluster_join.changed
  rescue:
  - debug:
      var: influxdb_master_node
  when: influxdb_cluster
  tags:
    - influxdb_debug
